
version: "3.9"

services:
  mongo:
    image: mongo:latest 
    container_name: dev-chefcontrol-mongo
    ports:
      - "27017:27017" 
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped 
  backend:
    build:
      context: ./backEnd 
      dockerfile: Dockerfile
    container_name: dev-chefcontrol-backend
    ports:
      - "3000:3000" 
    environment:
      - NODE_ENV=development
      - PORT=3000
      - MONGO_URI=mongodb://mongo:27017/lifefit
    volumes:
      - ./backEnd:/app
      - /app/node_modules
    depends_on:
      - mongo 
    restart: unless-stopped

  frontend:
    build:
      context: ./frontEnd/chefControl 
      dockerfile: Dockerfile.dev
    container_name: dev-chefcontrol-frontend
    ports:
      - "5173:5173" 
    volumes:
      - ./frontEnd/chefControl:/app
      - /app/node_modules
    depends_on:
      - backend

    restart: unless-stopped

volumes:
  mongo-data: 
    driver: local